# -*- coding: utf-8 -*-
"""breast_cancer_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQi64dmxX1CsrGUqV1sdPUrL0mTeYzBh

# Install Packages
"""

import os
import random
import shutil
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import transforms, models
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

from tqdm import tqdm

"""# DEVICE"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

"""# CONNECT DRIVE"""

from google.colab import drive
drive.mount('/content/drive')

"""# DATASET PATH"""

DATASET_PATH = "/content/drive/MyDrive/Data_Set/Deep_Learning/BreaKHis_v1/BreaKHis_v1/histology_slides/breast"

"""# PATIENT-WISE SPLIT"""

data = []

for cls in ["benign", "malignant"]:
    class_path = os.path.join(DATASET_PATH, cls)

    for root, _, files in os.walk(class_path):
        for file in files:
            if file.endswith(".png"):

                full_path = os.path.join(root, file)

                patient_id = file.split("-")[2]

                data.append([full_path, cls, patient_id])

df = pd.DataFrame(data, columns=["path", "label", "patient_id"])

"""# SPLIT PATIENTS"""

patients = df.groupby("patient_id")["label"].first().reset_index()

benign = patients[patients["label"]=="benign"]["patient_id"].tolist()
malignant = patients[patients["label"]=="malignant"]["patient_id"].tolist()

def split(lst, tr=0.7, va=0.15):
    random.seed(42)
    random.shuffle(lst)
    n = len(lst)

    t = int(n*tr)
    v = int(n*(tr+va))

    return lst[:t], lst[t:v], lst[v:]


ben_tr, ben_va, ben_te = split(benign)
mal_tr, mal_va, mal_te = split(malignant)

"""# BUILD DATAFRAMES"""

def filter_patients(p_list):
    return df[df["patient_id"].isin(p_list)]

train_df = pd.concat([filter_patients(ben_tr), filter_patients(mal_tr)])
val_df   = pd.concat([filter_patients(ben_va), filter_patients(mal_va)])
test_df  = pd.concat([filter_patients(ben_te), filter_patients(mal_te)])

"""# CREATE FOLDER STRUCTURE"""

OUT_DIR = "/content/drive/MyDrive/Data_Set/Deep_Learning/breakhis_split"

for split in ["train","val","test"]:
    for cls in ["benign","malignant"]:
        os.makedirs(os.path.join(OUT_DIR, split, cls), exist_ok=True)

"""# COPY IMAGES"""

def copy(df, split):
    for _, r in df.iterrows():
        dst = os.path.join(OUT_DIR, split, r["label"], os.path.basename(r["path"]))
        shutil.copy2(r["path"], dst)

copy(train_df, "train")
copy(val_df, "val")
copy(test_df, "test")

"""# TRANSFORMS"""

IMG_SIZE = 224

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(20),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])
])

test_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])
])

"""# DATASETS & LOADERS"""

train_dataset = ImageFolder(OUT_DIR+"/train", transform=train_transform)
val_dataset   = ImageFolder(OUT_DIR+"/val", transform=test_transform)
test_dataset  = ImageFolder(OUT_DIR+"/test", transform=test_transform)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader   = DataLoader(val_dataset, batch_size=32)
test_loader  = DataLoader(test_dataset, batch_size=32)

import torch
import torch.nn as nn
import torch.optim as optim

# Hyperparameters
IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 10
LEARNING_RATE = 1e-4

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", device)

"""# DenseNet121"""

from torchvision import models

model_DenseNet121 = models.densenet121(
    weights=models.DenseNet121_Weights.DEFAULT
)

model_DenseNet121.classifier = nn.Linear(
    model_DenseNet121.classifier.in_features,
    2
)

model_DenseNet121 = model_DenseNet121.to(device)

print(model_DenseNet121)

"""Training Function

This version stores:

Train Loss
Validation Loss
Train Accuracy
Validation Accuracy
"""

criterion = nn.CrossEntropyLoss()

optimizer = optim.AdamW(
    model_DenseNet121.parameters(),
    lr=LEARNING_RATE
)

from sklearn.metrics import accuracy_score
from tqdm import tqdm

train_losses = []
val_losses = []

train_accs = []
val_accs = []

def train_DenseNet121(model_DenseNet121):

    best_acc = 0

    for epoch in range(EPOCHS):

        # ---------------- TRAIN ----------------

        model_DenseNet121.train()

        running_loss = 0

        train_true = []
        train_pred = []

        for images, labels in tqdm(train_loader):

            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            outputs = model_DenseNet121(images)

            loss = criterion(outputs, labels)

            loss.backward()

            optimizer.step()

            running_loss += loss.item()

            preds = outputs.argmax(1)

            train_true.extend(labels.cpu().numpy())
            train_pred.extend(preds.cpu().numpy())

        train_loss = running_loss / len(train_loader)

        train_acc = accuracy_score(
            train_true,
            train_pred
        )

        # ---------------- VALIDATION ----------------

        model_DenseNet121.eval()

        val_running_loss = 0

        val_true = []
        val_pred = []

        with torch.no_grad():

            for images, labels in val_loader:

                images = images.to(device)
                labels = labels.to(device)

                outputs = model_DenseNet121(images)

                loss = criterion(outputs, labels)

                val_running_loss += loss.item()

                preds = outputs.argmax(1)

                val_true.extend(labels.cpu().numpy())
                val_pred.extend(preds.cpu().numpy())

        val_loss = val_running_loss / len(val_loader)

        val_acc = accuracy_score(
            val_true,
            val_pred
        )

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch [{epoch+1}/{EPOCHS}] "
            f"Train Loss={train_loss:.4f} "
            f"Train Acc={train_acc:.4f} "
            f"Val Loss={val_loss:.4f} "
            f"Val Acc={val_acc:.4f}"
        )

        if val_acc > best_acc:

            best_acc = val_acc

            torch.save(
                model_DenseNet121.state_dict(),
                "best_densenet121.pth"
            )

    print("Best Validation Accuracy:", best_acc)

train_DenseNet121(model_DenseNet121)

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))

plt.subplot(1,2,1)
plt.plot(train_accs, label='Train Accuracy')
plt.plot(val_accs, label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('DenseNet121 Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1,2,2)
plt.plot(train_losses, label='Train Loss')
plt.plot(val_losses, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('DenseNet121 Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()

plt.savefig(
    "DenseNet121_Training_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

model_DenseNet121.load_state_dict(
    torch.load("best_densenet121.pth")
)

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve
)

y_true = []
y_pred = []
y_prob = []

model_DenseNet121.eval()

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)

        outputs = model_DenseNet121(images)

        probs = torch.softmax(outputs, dim=1)

        preds = outputs.argmax(1)

        y_true.extend(labels.numpy())

        y_pred.extend(preds.cpu().numpy())

        y_prob.extend(
            probs[:,1].cpu().numpy()
        )

print(
    classification_report(
        y_true,
        y_pred,
        target_names=[
            "Benign",
            "Malignant"
        ]
    )
)

from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(
    y_true,
    y_pred
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Benign",
        "Malignant"
    ]
)

disp.plot()

plt.title("DenseNet121 Confusion Matrix")

plt.savefig(
    "DenseNet121_Confusion_Matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

fpr, tpr, _ = roc_curve(
    y_true,
    y_prob
)

auc_score = roc_auc_score(
    y_true,
    y_prob
)

plt.figure(figsize=(7,5))

plt.plot(
    fpr,
    tpr,
    label=f"AUC = {auc_score:.4f}"
)

plt.plot(
    [0,1],
    [0,1],
    "--"
)

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title("DenseNet121 ROC Curve")

plt.legend()

plt.savefig(
    "DenseNet121_ROC_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(y_true,y_pred))
print("Precision:", precision_score(y_true,y_pred))
print("Recall   :", recall_score(y_true,y_pred))
print("F1 Score :", f1_score(y_true,y_pred))
print("AUC      :", auc_score)

"""# EfficientNetB0"""

from torchvision import models
import torch.nn as nn

model_EfficientNetB0 = models.efficientnet_b0(
    weights=models.EfficientNet_B0_Weights.DEFAULT
)

model_EfficientNetB0.classifier[1] = nn.Linear(
    model_EfficientNetB0.classifier[1].in_features,
    2
)

model_EfficientNetB0 = model_EfficientNetB0.to(device)

print(model_EfficientNetB0)

"""Parameters"""

import torch.optim as optim
from sklearn.metrics import accuracy_score

criterion = nn.CrossEntropyLoss()

optimizer = optim.AdamW(
    model_EfficientNetB0.parameters(),
    lr=1e-4
)

"""Training Setup"""

train_losses, val_losses = [], []
train_accs, val_accs = [], []

"""Train Function"""

from tqdm import tqdm

def train_efficientnet(model_EfficientNetB0, epochs=10):

    best_acc = 0

    for epoch in range(epochs):

        # ---------------- TRAIN ----------------
        model_EfficientNetB0.train()

        running_loss = 0
        train_true, train_pred = [], []

        for x, y in tqdm(train_loader):

            x, y = x.to(device), y.to(device)

            optimizer.zero_grad()

            out = model_EfficientNetB0(x)

            loss = criterion(out, y)

            loss.backward()
            optimizer.step()

            running_loss += loss.item()

            preds = out.argmax(1)

            train_true.extend(y.cpu().numpy())
            train_pred.extend(preds.cpu().numpy())

        train_loss = running_loss / len(train_loader)
        train_acc = accuracy_score(train_true, train_pred)

        # ---------------- VALIDATION ----------------
        model_EfficientNetB0.eval()

        val_loss = 0
        val_true, val_pred = [], []

        with torch.no_grad():

            for x, y in val_loader:

                x, y = x.to(device), y.to(device)

                out = model_EfficientNetB0(x)

                loss = criterion(out, y)

                val_loss += loss.item()

                preds = out.argmax(1)

                val_true.extend(y.cpu().numpy())
                val_pred.extend(preds.cpu().numpy())

        val_loss = val_loss / len(val_loader)
        val_acc = accuracy_score(val_true, val_pred)

        # ---------------- save history ----------------
        train_losses.append(train_loss)
        val_losses.append(val_loss)
        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch {epoch+1}: "
            f"Train Acc={train_acc:.4f}, "
            f"Val Acc={val_acc:.4f}"
        )

        if val_acc > best_acc:
            best_acc = val_acc
            torch.save(model_EfficientNetB0.state_dict(), "best_efficientnet.pth")

    print("Best Val Accuracy:", best_acc)

train_efficientnet(model_EfficientNetB0)

"""Combined Accuracy + Loss Graph"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))

# ---------------- Accuracy ----------------
plt.subplot(1,2,1)
plt.plot(train_accs, label="Train Accuracy")
plt.plot(val_accs, label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("EfficientNetB0 Accuracy")
plt.legend()
plt.grid(True)

# ---------------- Loss ----------------
plt.subplot(1,2,2)
plt.plot(train_losses, label="Train Loss")
plt.plot(val_losses, label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("EfficientNetB0 Loss")
plt.legend()
plt.grid(True)

plt.savefig(
    "EfficientNetB0_Training_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.tight_layout()
plt.show()

"""Load Best Model"""

model_EfficientNetB0.load_state_dict(
    torch.load("best_efficientnet.pth")
)

"""Test Evaluation"""

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    roc_auc_score
)

y_true, y_pred, y_prob = [], [], []

model_EfficientNetB0.eval()

with torch.no_grad():

    for x, y in test_loader:

        x = x.to(device)

        out = model_EfficientNetB0(x)

        prob = torch.softmax(out, dim=1)[:,1]

        pred = out.argmax(1)

        y_true.extend(y.numpy())
        y_pred.extend(pred.cpu().numpy())
        y_prob.extend(prob.cpu().numpy())

"""Classification Report"""

print(
    classification_report(
        y_true,
        y_pred,
        target_names=["Benign", "Malignant"]
    )
)

"""Confusion Matrix"""

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(y_true, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Benign", "Malignant"]
)

disp.plot()

plt.title("EfficientNetB0 Confusion Matrix")

plt.savefig(
    "EfficientNetB0_Confusion_Matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""ROC Curve"""

fpr, tpr, _ = roc_curve(y_true, y_prob)

auc_score = roc_auc_score(y_true, y_prob)

plt.figure(figsize=(6,5))

plt.plot(fpr, tpr, label=f"AUC = {auc_score:.4f}")

plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title("EfficientNetB0 ROC Curve")

plt.legend()

plt.savefig(
    "EfficientNetB0_ROC_Curves.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(y_true,y_pred))
print("Precision:", precision_score(y_true,y_pred))
print("Recall   :", recall_score(y_true,y_pred))
print("F1 Score :", f1_score(y_true,y_pred))
print("AUC      :", auc_score)

"""# ResNet50"""

from torchvision import models
import torch.nn as nn

model_ResNet50 = models.resnet50(
    weights=models.ResNet50_Weights.DEFAULT
)

model_ResNet50.fc = nn.Linear(
    model_ResNet50.fc.in_features,
    2
)

model_ResNet50 = model_ResNet50.to(device)

print(model_ResNet50)

"""Parameters"""

import torch.optim as optim
from sklearn.metrics import accuracy_score

criterion = nn.CrossEntropyLoss()

optimizer = optim.AdamW(
    model_ResNet50.parameters(),
    lr=1e-4
)

"""Training History Containers"""

train_losses, val_losses = [], []
train_accs, val_accs = [], []

from tqdm import tqdm

def train_resnet(model_ResNet50, epochs=10):

    best_acc = 0

    for epoch in range(epochs):

        # ---------------- TRAIN ----------------
        model_ResNet50.train()

        running_loss = 0
        train_true, train_pred = [], []

        for x, y in tqdm(train_loader):

            x, y = x.to(device), y.to(device)

            optimizer.zero_grad()

            out = model_ResNet50(x)

            loss = criterion(out, y)

            loss.backward()

            optimizer.step()

            running_loss += loss.item()

            preds = out.argmax(1)

            train_true.extend(y.cpu().numpy())
            train_pred.extend(preds.cpu().numpy())

        train_loss = running_loss / len(train_loader)
        train_acc = accuracy_score(train_true, train_pred)

        # ---------------- VALIDATION ----------------
        model_ResNet50.eval()

        val_loss = 0
        val_true, val_pred = [], []

        with torch.no_grad():

            for x, y in val_loader:

                x, y = x.to(device), y.to(device)

                out = model_ResNet50(x)

                loss = criterion(out, y)

                val_loss += loss.item()

                preds = out.argmax(1)

                val_true.extend(y.cpu().numpy())
                val_pred.extend(preds.cpu().numpy())

        val_loss = val_loss / len(val_loader)
        val_acc = accuracy_score(val_true, val_pred)

        # ---------------- save history ----------------
        train_losses.append(train_loss)
        val_losses.append(val_loss)
        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch {epoch+1}: "
            f"Train Acc={train_acc:.4f}, "
            f"Val Acc={val_acc:.4f}"
        )

        if val_acc > best_acc:
            best_acc = val_acc
            torch.save(model_ResNet50.state_dict(), "best_resnet50.pth")

    print("Best Val Accuracy:", best_acc)

train_resnet(model_ResNet50)

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))

# ---------------- Accuracy ----------------
plt.subplot(1,2,1)
plt.plot(train_accs, label="Train Accuracy")
plt.plot(val_accs, label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("ResNet50 Accuracy")
plt.legend()
plt.grid(True)

# ---------------- Loss ----------------
plt.subplot(1,2,2)
plt.plot(train_losses, label="Train Loss")
plt.plot(val_losses, label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("ResNet50 Loss")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.savefig(
    "ResNet50_Training_Curves.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()

model_ResNet50.load_state_dict(
    torch.load("best_resnet50.pth")
)

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    roc_auc_score
)

y_true, y_pred, y_prob = [], [], []

model_ResNet50.eval()

with torch.no_grad():

    for x, y in test_loader:

        x = x.to(device)

        out = model_ResNet50(x)

        prob = torch.softmax(out, dim=1)[:,1]

        pred = out.argmax(1)

        y_true.extend(y.numpy())
        y_pred.extend(pred.cpu().numpy())
        y_prob.extend(prob.cpu().numpy())

print(
    classification_report(
        y_true,
        y_pred,
        target_names=["Benign", "Malignant"]
    )
)

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(y_true, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Benign", "Malignant"]
)

disp.plot()

plt.title("ResNet50 Confusion Matrix")

plt.tight_layout()
plt.savefig(
    "ResNet50_Confusion Matrixs.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

fpr, tpr, _ = roc_curve(y_true, y_prob)

auc_score = roc_auc_score(y_true, y_prob)

plt.figure(figsize=(6,5))

plt.plot(fpr, tpr, label=f"AUC = {auc_score:.4f}")

plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title("ResNet50 ROC Curve")

plt.legend()

plt.tight_layout()

plt.savefig(
    "ResNet50_ROC_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(y_true,y_pred))
print("Precision:", precision_score(y_true,y_pred))
print("Recall   :", recall_score(y_true,y_pred))
print("F1 Score :", f1_score(y_true,y_pred))
print("AUC      :", auc_score)

"""# Vision Transformer (ViT-B/16)"""

from torchvision import models
import torch.nn as nn

model_ViT = models.vit_b_16(
    weights=models.ViT_B_16_Weights.DEFAULT
)

model_ViT.heads.head = nn.Linear(
    model_ViT.heads.head.in_features,
    2
)

model_ViT = model_ViT.to(device)

print(model_ViT)

"""Parameters"""

import torch.optim as optim
from sklearn.metrics import accuracy_score

criterion = nn.CrossEntropyLoss()

optimizer = optim.AdamW(
    model_ViT.parameters(),
    lr=1e-4,
    weight_decay=1e-4
)

"""Training History"""

train_losses = []
val_losses = []

train_accs = []
val_accs = []

"""Training Function"""

from tqdm import tqdm

def train_vit(model_ViT, epochs=10):

    best_acc = 0

    for epoch in range(epochs):

        # ---------------- TRAIN ----------------

        model_ViT.train()

        running_loss = 0

        train_true = []
        train_pred = []

        for images, labels in tqdm(train_loader):

            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            outputs = model_ViT(images)

            loss = criterion(
                outputs,
                labels
            )

            loss.backward()

            optimizer.step()

            running_loss += loss.item()

            preds = outputs.argmax(1)

            train_true.extend(
                labels.cpu().numpy()
            )

            train_pred.extend(
                preds.cpu().numpy()
            )

        train_loss = running_loss / len(train_loader)

        train_acc = accuracy_score(
            train_true,
            train_pred
        )

        # ---------------- VALIDATION ----------------

        model_ViT.eval()

        val_running_loss = 0

        val_true = []
        val_pred = []

        with torch.no_grad():

            for images, labels in val_loader:

                images = images.to(device)
                labels = labels.to(device)

                outputs = model_ViT(images)

                loss = criterion(
                    outputs,
                    labels
                )

                val_running_loss += loss.item()

                preds = outputs.argmax(1)

                val_true.extend(
                    labels.cpu().numpy()
                )

                val_pred.extend(
                    preds.cpu().numpy()
                )

        val_loss = val_running_loss / len(val_loader)

        val_acc = accuracy_score(
            val_true,
            val_pred
        )

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch {epoch+1}: "
            f"Train Acc={train_acc:.4f} "
            f"Val Acc={val_acc:.4f}"
        )

        if val_acc > best_acc:

            best_acc = val_acc

            torch.save(
                model_ViT.state_dict(),
                "best_vit.pth"
            )

    print(
        "Best Validation Accuracy:",
        best_acc
    )

"""Train ViT"""

train_vit(
    model_ViT,
    epochs=10
)

"""Combined Accuracy + Loss Graph"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))

# ---------------- Accuracy ----------------

plt.subplot(1,2,1)

plt.plot(
    train_accs,
    label='Train Accuracy'
)

plt.plot(
    val_accs,
    label='Validation Accuracy'
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.title(
    "ViT-B16 Accuracy"
)

plt.legend()

plt.grid(True)

# ---------------- Loss ----------------

plt.subplot(1,2,2)

plt.plot(
    train_losses,
    label='Train Loss'
)

plt.plot(
    val_losses,
    label='Validation Loss'
)

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.title(
    "ViT-B16 Loss"
)

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.savefig(
    "ViT-B16_Training_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""Load Best Model"""

model_ViT.load_state_dict(
    torch.load(
        "best_vit.pth"
    )
)

"""Test Evaluation"""

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    roc_auc_score
)

y_true = []
y_pred = []
y_prob = []

model_ViT.eval()

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)

        outputs = model_ViT(images)

        probs = torch.softmax(
            outputs,
            dim=1
        )

        preds = outputs.argmax(1)

        y_true.extend(
            labels.numpy()
        )

        y_pred.extend(
            preds.cpu().numpy()
        )

        y_prob.extend(
            probs[:,1].cpu().numpy()
        )

"""Classification Report"""

print(
    classification_report(
        y_true,
        y_pred,
        target_names=[
            "Benign",
            "Malignant"
        ]
    )
)

"""Confusion Matrix"""

from sklearn.metrics import (
    ConfusionMatrixDisplay
)

cm = confusion_matrix(
    y_true,
    y_pred
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Benign",
        "Malignant"
    ]
)

disp.plot()

plt.title(
    "ViT-B16 Confusion Matrix"
)

plt.savefig(
    "ViT-B16_Confusion_Matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""ROC Curve"""

fpr, tpr, _ = roc_curve(
    y_true,
    y_prob
)

auc_score = roc_auc_score(
    y_true,
    y_prob
)

plt.figure(
    figsize=(6,5)
)

plt.plot(
    fpr,
    tpr,
    label=f"AUC = {auc_score:.4f}"
)

plt.plot(
    [0,1],
    [0,1],
    '--'
)

plt.xlabel(
    "False Positive Rate"
)

plt.ylabel(
    "True Positive Rate"
)

plt.title(
    "ViT-B16 ROC Curve"
)

plt.legend()

plt.savefig(
    "ViT-B16_ROC_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""Final Metrics"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print(
    "Accuracy:",
    accuracy_score(
        y_true,
        y_pred
    )
)

print(
    "Precision:",
    precision_score(
        y_true,
        y_pred
    )
)

print(
    "Recall:",
    recall_score(
        y_true,
        y_pred
    )
)

print(
    "F1 Score:",
    f1_score(
        y_true,
        y_pred
    )
)

print(
    "AUC:",
    auc_score
)

"""# Xception

Install & Import
"""

!pip install timm -q

import timm
import torch
import torch.nn as nn

"""Model Code"""

model_xception = timm.create_model(
    'xception',
    pretrained=True,
    num_classes=2
)

model_xception = model_xception.to(device)

print(model_xception)

"""Parameters"""

import torch.optim as optim
from sklearn.metrics import accuracy_score

criterion = nn.CrossEntropyLoss()

optimizer = optim.AdamW(
    model_xception.parameters(),
    lr=1e-4,
    weight_decay=1e-4
)

"""Training History"""

train_losses = []
val_losses = []

train_accs = []
val_accs = []

"""Training Function"""

from tqdm import tqdm

def train_xception(model_xception, epochs=10):

    best_acc = 0

    for epoch in range(epochs):

        # ---------------- TRAIN ----------------
        model_xception.train()

        running_loss = 0

        train_true = []
        train_pred = []

        for images, labels in tqdm(train_loader):

            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            outputs = model_xception(images)

            loss = criterion(outputs, labels)

            loss.backward()

            optimizer.step()

            running_loss += loss.item()

            preds = outputs.argmax(1)

            train_true.extend(labels.cpu().numpy())
            train_pred.extend(preds.cpu().numpy())

        train_loss = running_loss / len(train_loader)

        train_acc = accuracy_score(
            train_true,
            train_pred
        )

        # ---------------- VALIDATION ----------------
        model_xception.eval()

        val_running_loss = 0

        val_true = []
        val_pred = []

        with torch.no_grad():

            for images, labels in val_loader:

                images = images.to(device)
                labels = labels.to(device)

                outputs = model_xception(images)

                loss = criterion(outputs, labels)

                val_running_loss += loss.item()

                preds = outputs.argmax(1)

                val_true.extend(labels.cpu().numpy())
                val_pred.extend(preds.cpu().numpy())

        val_loss = val_running_loss / len(val_loader)

        val_acc = accuracy_score(
            val_true,
            val_pred
        )

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch {epoch+1}: "
            f"Train Acc={train_acc:.4f} "
            f"Val Acc={val_acc:.4f}"
        )

        if val_acc > best_acc:

            best_acc = val_acc

            torch.save(
                model_xception.state_dict(),
                "best_xception.pth"
            )

    print(
        "Best Validation Accuracy:",
        best_acc
    )

"""Train Model"""

train_xception(
    model_xception,
    epochs=10
)

"""Accuracy + Loss Graph"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))

# ---------------- Accuracy ----------------
plt.subplot(1,2,1)

plt.plot(
    train_accs,
    label="Train Accuracy"
)

plt.plot(
    val_accs,
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.title(
    "Xception Accuracy"
)

plt.legend()
plt.grid(True)

# ---------------- Loss ----------------
plt.subplot(1,2,2)

plt.plot(
    train_losses,
    label="Train Loss"
)

plt.plot(
    val_losses,
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.title(
    "Xception Loss"
)

plt.legend()
plt.grid(True)

plt.tight_layout()

plt.savefig(
    "Xception_Training_Curves.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()

"""Load Best Model"""

model_xception.load_state_dict(
    torch.load(
        "best_xception.pth"
    )
)

"""Test Evaluation"""

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    roc_auc_score
)

y_true = []
y_pred = []
y_prob = []

model_xception.eval()

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)

        outputs = model_xception(images)

        probs = torch.softmax(
            outputs,
            dim=1
        )

        preds = outputs.argmax(1)

        y_true.extend(
            labels.numpy()
        )

        y_pred.extend(
            preds.cpu().numpy()
        )

        y_prob.extend(
            probs[:,1].cpu().numpy()
        )

"""Classification Report"""

print(
    classification_report(
        y_true,
        y_pred,
        target_names=[
            "Benign",
            "Malignant"
        ]
    )
)

"""Confusion Matrix"""

from sklearn.metrics import (
    ConfusionMatrixDisplay
)

cm = confusion_matrix(
    y_true,
    y_pred
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Benign",
        "Malignant"
    ]
)

disp.plot()

plt.title(
    "Xception Confusion Matrix"
)

plt.savefig(
    "Xception_Confusion_Matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""ROC Curve"""

fpr, tpr, _ = roc_curve(
    y_true,
    y_prob
)

auc_score = roc_auc_score(
    y_true,
    y_prob
)

plt.figure(figsize=(6,5))

plt.plot(
    fpr,
    tpr,
    label=f"AUC = {auc_score:.4f}"
)

plt.plot(
    [0,1],
    [0,1],
    '--'
)

plt.xlabel(
    "False Positive Rate"
)

plt.ylabel(
    "True Positive Rate"
)

plt.title(
    "Xception ROC Curve"
)

plt.legend()

plt.savefig(
    "Xception_ROC_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""Final Metrics"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(y_true, y_pred))
print("Precision:", precision_score(y_true, y_pred))
print("Recall   :", recall_score(y_true, y_pred))
print("F1 Score :", f1_score(y_true, y_pred))
print("AUC      :", auc_score)

"""# MobileNetV3"""

from torchvision import models
import torch.nn as nn

model_MobileNetV3 = models.mobilenet_v3_large(
    weights=models.MobileNet_V3_Large_Weights.DEFAULT
)

model_MobileNetV3.classifier[3] = nn.Linear(
    model_MobileNetV3.classifier[3].in_features,
    2
)

model_MobileNetV3 = model_MobileNetV3.to(device)

print(model_MobileNetV3)

"""Parameters"""

import torch.optim as optim
from sklearn.metrics import accuracy_score

criterion = nn.CrossEntropyLoss()

optimizer = optim.AdamW(
    model_MobileNetV3.parameters(),
    lr=1e-4,
    weight_decay=1e-4
)

"""Training History"""

train_losses = []
val_losses = []

train_accs = []
val_accs = []

"""Training Function"""

from tqdm import tqdm

def train_mobilenet(model_MobileNetV3, epochs=10):

    best_acc = 0

    for epoch in range(epochs):

        # ---------------- TRAIN ----------------
        model_MobileNetV3.train()

        running_loss = 0

        train_true = []
        train_pred = []

        for images, labels in tqdm(train_loader):

            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            outputs = model_MobileNetV3(images)

            loss = criterion(outputs, labels)

            loss.backward()

            optimizer.step()

            running_loss += loss.item()

            preds = outputs.argmax(1)

            train_true.extend(labels.cpu().numpy())
            train_pred.extend(preds.cpu().numpy())

        train_loss = running_loss / len(train_loader)

        train_acc = accuracy_score(
            train_true,
            train_pred
        )

        # ---------------- VALIDATION ----------------
        model_MobileNetV3.eval()

        val_running_loss = 0

        val_true = []
        val_pred = []

        with torch.no_grad():

            for images, labels in val_loader:

                images = images.to(device)
                labels = labels.to(device)

                outputs = model_MobileNetV3(images)

                loss = criterion(outputs, labels)

                val_running_loss += loss.item()

                preds = outputs.argmax(1)

                val_true.extend(labels.cpu().numpy())
                val_pred.extend(preds.cpu().numpy())

        val_loss = val_running_loss / len(val_loader)

        val_acc = accuracy_score(
            val_true,
            val_pred
        )

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch {epoch+1}: "
            f"Train Acc={train_acc:.4f} "
            f"Val Acc={val_acc:.4f}"
        )

        if val_acc > best_acc:

            best_acc = val_acc

            torch.save(
                model_MobileNetV3.state_dict(),
                "best_mobilenetv3.pth"
            )

    print(
        "Best Validation Accuracy:",
        best_acc
    )

"""Train Model"""

train_mobilenet(
    model_MobileNetV3,
    epochs=10
)

"""Combined Accuracy + Loss Graph"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))

# ---------------- Accuracy ----------------
plt.subplot(1,2,1)

plt.plot(
    train_accs,
    label='Train Accuracy'
)

plt.plot(
    val_accs,
    label='Validation Accuracy'
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.title(
    "MobileNetV3 Accuracy"
)

plt.legend()
plt.grid(True)

# ---------------- Loss ----------------
plt.subplot(1,2,2)

plt.plot(
    train_losses,
    label='Train Loss'
)

plt.plot(
    val_losses,
    label='Validation Loss'
)

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.title(
    "MobileNetV3 Loss"
)

plt.legend()
plt.grid(True)

plt.tight_layout()

plt.savefig(
    "MobileNetV3_Training_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""Load Best Model"""

model_MobileNetV3.load_state_dict(
    torch.load(
        "best_mobilenetv3.pth"
    )
)

"""Test Evaluation"""

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    roc_auc_score
)

y_true = []
y_pred = []
y_prob = []

model_MobileNetV3.eval()

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model_MobileNetV3(images)

        probs = torch.softmax(
            outputs,
            dim=1
        )

        preds = outputs.argmax(1)

        y_true.extend(
            labels.cpu().numpy()
        )

        y_pred.extend(
            preds.cpu().numpy()
        )

        y_prob.extend(
            probs[:, 1].cpu().numpy()
        )

"""Classification Report"""

print(
    classification_report(
        y_true,
        y_pred,
        target_names=[
            "Benign",
            "Malignant"
        ]
    )
)

"""Confusion Matrix"""

from sklearn.metrics import (
    ConfusionMatrixDisplay
)

cm = confusion_matrix(
    y_true,
    y_pred
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Benign",
        "Malignant"
    ]
)

disp.plot()

plt.title(
    "MobileNetV3 Confusion Matrix"
)

plt.savefig(
    "MobileNetV3_Confusion_Matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""ROC Curve"""

fpr, tpr, _ = roc_curve(
    y_true,
    y_prob
)

auc_score = roc_auc_score(
    y_true,
    y_prob
)

plt.figure(
    figsize=(6,5)
)

plt.plot(
    fpr,
    tpr,
    label=f"AUC = {auc_score:.4f}"
)

plt.plot(
    [0,1],
    [0,1],
    '--'
)

plt.xlabel(
    "False Positive Rate"
)

plt.ylabel(
    "True Positive Rate"
)

plt.title(
    "MobileNetV3 ROC Curve"
)

plt.legend()

plt.savefig(
    "MobileNetV3_ROC_Curves.png",
    dpi=300,
    bbox_inches="tight"
)


plt.show()

"""# Final Metrics"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print(
    "Accuracy:",
    accuracy_score(
        y_true,
        y_pred
    )
)

print(
    "Precision:",
    precision_score(
        y_true,
        y_pred
    )
)

print(
    "Recall:",
    recall_score(
        y_true,
        y_pred
    )
)

print(
    "F1 Score:",
    f1_score(
        y_true,
        y_pred
    )
)

print(
    "AUC:",
    auc_score
)

"""# Grad Cam ++"""

!pip install grad-cam -q

import torch
import numpy as np
import matplotlib.pyplot as plt

from pytorch_grad_cam import GradCAMPlusPlus
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model_MobileNetV3.load_state_dict(
    torch.load("best_mobilenetv3.pth", map_location=device)
)

model_MobileNetV3.to(device)
model_MobileNetV3.eval()

target_layers = [model_MobileNetV3.features[-1]]

def prepare_image(img_tensor):

    img = img_tensor.permute(1, 2, 0).cpu().numpy()

    img = (img - img.min()) / (img.max() - img.min() + 1e-8)

    return img

images, labels = next(iter(test_loader))

image_tensor = images[0].unsqueeze(0).to(device)
label = labels[0].item()

from pytorch_grad_cam import GradCAMPlusPlus
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget

cam = GradCAMPlusPlus(
    model=model_MobileNetV3,
    target_layers=target_layers
)

model_MobileNetV3 = model_MobileNetV3.to(device)
model_MobileNetV3.eval()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


target_layers = [model_MobileNetV3.features[-1]]

cam = GradCAMPlusPlus(
    model=model_MobileNetV3,
    target_layers=target_layers
)

images, labels = next(iter(test_loader))

img = images[0].unsqueeze(0).to(device)

targets = [ClassifierOutputTarget(labels[0].item())]

grayscale_cam = cam(
    input_tensor=img,
    targets=targets
)[0]

import matplotlib.pyplot as plt

def prepare_image(img_tensor):
    img = img_tensor.permute(1,2,0).cpu().numpy()
    img = (img - img.min()) / (img.max() - img.min() + 1e-8)
    return img

image = prepare_image(images[0])

visualization = show_cam_on_image(
    image,
    grayscale_cam,
    use_rgb=True
)

plt.imshow(visualization)
plt.axis("off")
plt.title("MobileNetV3 Grad-CAM++")
plt.savefig(
    "MobileNetV3_Grad_CAM_Plus.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()

"""## Final Comparison Table"""

import pandas as pd
import matplotlib.pyplot as plt

# ---------------- Final Results ----------------
results = {
    "Model": [
        "Xception",
        "DenseNet121",
        "MobileNetV3",
        "ResNet50",
        "EfficientNetB0",
        "ViT-B/16"
    ],
    "Accuracy": [
        0.7937710437710438,
        0.7617845117845118,
        0.8181818181818182,
        0.8148148148148148,
        0.7828282828282829,
        0.8156565656565656
    ],
    "Precision": [
        0.8107142857142857,
        0.8055555555555556,
        0.8465408805031447,
        0.8423028785982478,
        0.8300907911802854,
        0.8269689737470167
    ],
    "Recall": [
        0.8878748370273793,
        0.8318122555410691,
        0.877444589308996,
        0.877444589308996,
        0.834419817470665,
        0.9035202086049544
    ],
    "F1-score": [
        0.8475420037336652,
        0.8184733803720333,
        0.8617157490396927,
        0.859514687100894,
        0.8322496749024707,
        0.8635514018691589
    ],
    "AUC": [
        0.8445790893353194,
        0.8403936737202972,
        0.8499877673757461,
        0.8854561839786689,
        0.8503268743012694,
        0.8838783302932425
    ]
}

df = pd.DataFrame(results)

# ---------------- Sort by F1-score (optional) ----------------
df = df.sort_values("F1-score", ascending=False)

print(df)

# ---------------- Create Table Figure ----------------
fig, ax = plt.subplots(figsize=(12, 3))
ax.axis('off')

table = ax.table(
    cellText=df.round(4).values,
    colLabels=df.columns,
    cellLoc='center',
    loc='center'
)

table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1.2, 1.6)

plt.title("Performance Comparison of Deep Learning Models on BreakHis Dataset",
          fontsize=12,
          pad=20)

plt.savefig(
    "Model_Comparison_Table.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()