# -*- coding: utf-8 -*-
"""breast_cancer_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzoUNktGo-xM02bNZ51Zu9IBAd2PYWc1

* Cell 1 : Install & Import Libraries
* Cell 2 : Dataset Loading
* Cell 3 : Data Augmentation
* Cell 4 : Create DataLoaders
* Cell 5 : Class Weights
* Cell 6 : Model Selection
* Cell 7 : Training Functions
* Cell 8 : Train DenseNet121
* Cell 9 : Train EfficientNetB0
* Cell 10: Train ResNet50
* Cell 11: Evaluate Models
* Cell 12: ROC Curve
* Cell 13: Confusion Matrix
* Cell 14: Grad-CAM++
* Cell 15: Final Comparison Table

# Install Packages
"""

import os
import random
import shutil
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import transforms, models
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

from tqdm import tqdm

"""# DEVICE"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

"""## Connect Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""# DATASET PATH"""

DATASET_PATH = "/content/drive/MyDrive/Data_Set/Deep_Learning/BreaKHis_v1/BreaKHis_v1/histology_slides/breast"

"""# PATIENT-WISE SPLIT"""

data = []

for cls in ["benign", "malignant"]:
    class_path = os.path.join(DATASET_PATH, cls)

    for root, _, files in os.walk(class_path):
        for file in files:
            if file.endswith(".png"):

                full_path = os.path.join(root, file)

                patient_id = file.split("-")[2]

                data.append([full_path, cls, patient_id])

df = pd.DataFrame(data, columns=["path", "label", "patient_id"])

"""# SPLIT PATIENTS"""

patients = df.groupby("patient_id")["label"].first().reset_index()

benign = patients[patients["label"]=="benign"]["patient_id"].tolist()
malignant = patients[patients["label"]=="malignant"]["patient_id"].tolist()

def split(lst, tr=0.7, va=0.15):
    random.seed(42)
    random.shuffle(lst)
    n = len(lst)

    t = int(n*tr)
    v = int(n*(tr+va))

    return lst[:t], lst[t:v], lst[v:]


ben_tr, ben_va, ben_te = split(benign)
mal_tr, mal_va, mal_te = split(malignant)

"""# BUILD DATAFRAMES"""

def filter_patients(p_list):
    return df[df["patient_id"].isin(p_list)]

train_df = pd.concat([filter_patients(ben_tr), filter_patients(mal_tr)])
val_df   = pd.concat([filter_patients(ben_va), filter_patients(mal_va)])
test_df  = pd.concat([filter_patients(ben_te), filter_patients(mal_te)])

"""# CREATE FOLDER STRUCTURE"""

OUT_DIR = "/content/drive/MyDrive/Data_Set/Deep_Learning/breakhis_split"

for split in ["train","val","test"]:
    for cls in ["benign","malignant"]:
        os.makedirs(os.path.join(OUT_DIR, split, cls), exist_ok=True)

"""# COPY IMAGES"""

def copy(df, split):
    for _, r in df.iterrows():
        dst = os.path.join(OUT_DIR, split, r["label"], os.path.basename(r["path"]))
        shutil.copy2(r["path"], dst)

copy(train_df, "train")
copy(val_df, "val")
copy(test_df, "test")

"""# TRANSFORMS"""

IMG_SIZE = 224

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(20),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])
])

test_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])
])

"""# DATASETS & LOADERS"""

train_dataset = ImageFolder(OUT_DIR+"/train", transform=train_transform)
val_dataset   = ImageFolder(OUT_DIR+"/val", transform=test_transform)
test_dataset  = ImageFolder(OUT_DIR+"/test", transform=test_transform)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader   = DataLoader(val_dataset, batch_size=32)
test_loader  = DataLoader(test_dataset, batch_size=32)

import torch
import torch.nn as nn
import torch.optim as optim

# Hyperparameters
IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 10
LEARNING_RATE = 1e-4

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", device)

"""# DenseNet121"""

from torchvision import models

model = models.densenet121(
    weights=models.DenseNet121_Weights.DEFAULT
)

model.classifier = nn.Linear(
    model.classifier.in_features,
    2
)

model = model.to(device)

print(model)

"""Training Function

This version stores:

Train Loss
Validation Loss
Train Accuracy
Validation Accuracy
"""

criterion = nn.CrossEntropyLoss()

optimizer = optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE
)

from sklearn.metrics import accuracy_score
from tqdm import tqdm

train_losses = []
val_losses = []

train_accs = []
val_accs = []

def train_model(model):

    best_acc = 0

    for epoch in range(EPOCHS):

        ##################
        # TRAIN
        ##################

        model.train()

        running_loss = 0

        train_true = []
        train_pred = []

        for images, labels in tqdm(train_loader):

            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            outputs = model(images)

            loss = criterion(outputs, labels)

            loss.backward()

            optimizer.step()

            running_loss += loss.item()

            preds = outputs.argmax(1)

            train_true.extend(labels.cpu().numpy())
            train_pred.extend(preds.cpu().numpy())

        train_loss = running_loss / len(train_loader)

        train_acc = accuracy_score(
            train_true,
            train_pred
        )

        ##################
        # VALIDATION
        ##################

        model.eval()

        val_running_loss = 0

        val_true = []
        val_pred = []

        with torch.no_grad():

            for images, labels in val_loader:

                images = images.to(device)
                labels = labels.to(device)

                outputs = model(images)

                loss = criterion(outputs, labels)

                val_running_loss += loss.item()

                preds = outputs.argmax(1)

                val_true.extend(labels.cpu().numpy())
                val_pred.extend(preds.cpu().numpy())

        val_loss = val_running_loss / len(val_loader)

        val_acc = accuracy_score(
            val_true,
            val_pred
        )

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch [{epoch+1}/{EPOCHS}] "
            f"Train Loss={train_loss:.4f} "
            f"Train Acc={train_acc:.4f} "
            f"Val Loss={val_loss:.4f} "
            f"Val Acc={val_acc:.4f}"
        )

        if val_acc > best_acc:

            best_acc = val_acc

            torch.save(
                model.state_dict(),
                "best_densenet121.pth"
            )

    print("Best Validation Accuracy:", best_acc)

train_model(model)

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))

plt.subplot(1,2,1)
plt.plot(train_accs, label='Train Accuracy')
plt.plot(val_accs, label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('DenseNet121 Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1,2,2)
plt.plot(train_losses, label='Train Loss')
plt.plot(val_losses, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('DenseNet121 Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()

plt.savefig(
    "DenseNet121_Training_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

model.load_state_dict(
    torch.load("best_densenet121.pth")
)

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve
)

y_true = []
y_pred = []
y_prob = []

model.eval()

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)

        outputs = model(images)

        probs = torch.softmax(outputs, dim=1)

        preds = outputs.argmax(1)

        y_true.extend(labels.numpy())

        y_pred.extend(preds.cpu().numpy())

        y_prob.extend(
            probs[:,1].cpu().numpy()
        )

print(
    classification_report(
        y_true,
        y_pred,
        target_names=[
            "Benign",
            "Malignant"
        ]
    )
)

from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(
    y_true,
    y_pred
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Benign",
        "Malignant"
    ]
)

disp.plot()

plt.title("DenseNet121 Confusion Matrix")

plt.savefig(
    "DenseNet121_Confusion_Matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

fpr, tpr, _ = roc_curve(
    y_true,
    y_prob
)

auc_score = roc_auc_score(
    y_true,
    y_prob
)

plt.figure(figsize=(7,5))

plt.plot(
    fpr,
    tpr,
    label=f"AUC = {auc_score:.4f}"
)

plt.plot(
    [0,1],
    [0,1],
    "--"
)

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title("DenseNet121 ROC Curve")

plt.legend()

plt.savefig(
    "DenseNet121_ROC_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(y_true,y_pred))
print("Precision:", precision_score(y_true,y_pred))
print("Recall   :", recall_score(y_true,y_pred))
print("F1 Score :", f1_score(y_true,y_pred))
print("AUC      :", auc_score)

"""# EfficientNetB0"""

from torchvision import models
import torch.nn as nn

model = models.efficientnet_b0(
    weights=models.EfficientNet_B0_Weights.DEFAULT
)

model.classifier[1] = nn.Linear(
    model.classifier[1].in_features,
    2
)

model = model.to(device)

print(model)

"""Parameters"""

import torch.optim as optim
from sklearn.metrics import accuracy_score

criterion = nn.CrossEntropyLoss()

optimizer = optim.AdamW(
    model.parameters(),
    lr=1e-4
)

"""Training Setup"""

train_losses, val_losses = [], []
train_accs, val_accs = [], []

"""Train Function"""

from tqdm import tqdm

def train_efficientnet(model, epochs=10):

    best_acc = 0

    for epoch in range(epochs):

        # ---------------- TRAIN ----------------
        model.train()

        running_loss = 0
        train_true, train_pred = [], []

        for x, y in tqdm(train_loader):

            x, y = x.to(device), y.to(device)

            optimizer.zero_grad()

            out = model(x)

            loss = criterion(out, y)

            loss.backward()
            optimizer.step()

            running_loss += loss.item()

            preds = out.argmax(1)

            train_true.extend(y.cpu().numpy())
            train_pred.extend(preds.cpu().numpy())

        train_loss = running_loss / len(train_loader)
        train_acc = accuracy_score(train_true, train_pred)

        # ---------------- VALIDATION ----------------
        model.eval()

        val_loss = 0
        val_true, val_pred = [], []

        with torch.no_grad():

            for x, y in val_loader:

                x, y = x.to(device), y.to(device)

                out = model(x)

                loss = criterion(out, y)

                val_loss += loss.item()

                preds = out.argmax(1)

                val_true.extend(y.cpu().numpy())
                val_pred.extend(preds.cpu().numpy())

        val_loss = val_loss / len(val_loader)
        val_acc = accuracy_score(val_true, val_pred)

        # save history
        train_losses.append(train_loss)
        val_losses.append(val_loss)
        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch {epoch+1}: "
            f"Train Acc={train_acc:.4f}, "
            f"Val Acc={val_acc:.4f}"
        )

        if val_acc > best_acc:
            best_acc = val_acc
            torch.save(model.state_dict(), "best_efficientnet.pth")

    print("Best Val Accuracy:", best_acc)

train_efficientnet(model)

"""Combined Accuracy + Loss Graph"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))

# Accuracy
plt.subplot(1,2,1)
plt.plot(train_accs, label="Train Accuracy")
plt.plot(val_accs, label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("EfficientNetB0 Accuracy")
plt.legend()
plt.grid(True)

# Loss
plt.subplot(1,2,2)
plt.plot(train_losses, label="Train Loss")
plt.plot(val_losses, label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("EfficientNetB0 Loss")
plt.legend()
plt.grid(True)

plt.savefig(
    "EfficientNetB0_Training_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.tight_layout()
plt.show()

"""Load Best Model"""

model.load_state_dict(
    torch.load("best_efficientnet.pth")
)

"""Test Evaluation"""

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    roc_auc_score
)

y_true, y_pred, y_prob = [], [], []

model.eval()

with torch.no_grad():

    for x, y in test_loader:

        x = x.to(device)

        out = model(x)

        prob = torch.softmax(out, dim=1)[:,1]

        pred = out.argmax(1)

        y_true.extend(y.numpy())
        y_pred.extend(pred.cpu().numpy())
        y_prob.extend(prob.cpu().numpy())

"""Classification Report"""

print(
    classification_report(
        y_true,
        y_pred,
        target_names=["Benign", "Malignant"]
    )
)

"""Confusion Matrix"""

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(y_true, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Benign", "Malignant"]
)

disp.plot()

plt.title("EfficientNetB0 Confusion Matrix")

plt.savefig(
    "EfficientNetB0_Confusion_Matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""ROC Curve"""

fpr, tpr, _ = roc_curve(y_true, y_prob)

auc_score = roc_auc_score(y_true, y_prob)

plt.figure(figsize=(6,5))

plt.plot(fpr, tpr, label=f"AUC = {auc_score:.4f}")

plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title("EfficientNetB0 ROC Curve")

plt.legend()

plt.savefig(
    "EfficientNetB0_ROC_Curves.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(y_true,y_pred))
print("Precision:", precision_score(y_true,y_pred))
print("Recall   :", recall_score(y_true,y_pred))
print("F1 Score :", f1_score(y_true,y_pred))
print("AUC      :", auc_score)

"""# ResNet50"""

from torchvision import models
import torch.nn as nn

model = models.resnet50(
    weights=models.ResNet50_Weights.DEFAULT
)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model = model.to(device)

print(model)

"""Parameters"""

import torch.optim as optim
from sklearn.metrics import accuracy_score

criterion = nn.CrossEntropyLoss()

optimizer = optim.AdamW(
    model.parameters(),
    lr=1e-4
)

"""Training History Containers"""

train_losses, val_losses = [], []
train_accs, val_accs = [], []

from tqdm import tqdm

def train_resnet(model, epochs=10):

    best_acc = 0

    for epoch in range(epochs):

        # ---------------- TRAIN ----------------
        model.train()

        running_loss = 0
        train_true, train_pred = [], []

        for x, y in tqdm(train_loader):

            x, y = x.to(device), y.to(device)

            optimizer.zero_grad()

            out = model(x)

            loss = criterion(out, y)

            loss.backward()

            optimizer.step()

            running_loss += loss.item()

            preds = out.argmax(1)

            train_true.extend(y.cpu().numpy())
            train_pred.extend(preds.cpu().numpy())

        train_loss = running_loss / len(train_loader)
        train_acc = accuracy_score(train_true, train_pred)

        # ---------------- VALIDATION ----------------
        model.eval()

        val_loss = 0
        val_true, val_pred = [], []

        with torch.no_grad():

            for x, y in val_loader:

                x, y = x.to(device), y.to(device)

                out = model(x)

                loss = criterion(out, y)

                val_loss += loss.item()

                preds = out.argmax(1)

                val_true.extend(y.cpu().numpy())
                val_pred.extend(preds.cpu().numpy())

        val_loss = val_loss / len(val_loader)
        val_acc = accuracy_score(val_true, val_pred)

        # save history
        train_losses.append(train_loss)
        val_losses.append(val_loss)
        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch {epoch+1}: "
            f"Train Acc={train_acc:.4f}, "
            f"Val Acc={val_acc:.4f}"
        )

        if val_acc > best_acc:
            best_acc = val_acc
            torch.save(model.state_dict(), "best_resnet50.pth")

    print("Best Val Accuracy:", best_acc)

train_resnet(model)

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))

# Accuracy
plt.subplot(1,2,1)
plt.plot(train_accs, label="Train Accuracy")
plt.plot(val_accs, label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("ResNet50 Accuracy")
plt.legend()
plt.grid(True)

# Loss
plt.subplot(1,2,2)
plt.plot(train_losses, label="Train Loss")
plt.plot(val_losses, label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("ResNet50 Loss")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.savefig(
    "ResNet50_Training_Curves.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()

model.load_state_dict(
    torch.load("best_resnet50.pth")
)

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    roc_auc_score
)

y_true, y_pred, y_prob = [], [], []

model.eval()

with torch.no_grad():

    for x, y in test_loader:

        x = x.to(device)

        out = model(x)

        prob = torch.softmax(out, dim=1)[:,1]

        pred = out.argmax(1)

        y_true.extend(y.numpy())
        y_pred.extend(pred.cpu().numpy())
        y_prob.extend(prob.cpu().numpy())

print(
    classification_report(
        y_true,
        y_pred,
        target_names=["Benign", "Malignant"]
    )
)

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(y_true, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Benign", "Malignant"]
)

disp.plot()

plt.title("ResNet50 Confusion Matrix")

plt.tight_layout()
plt.savefig(
    "ResNet50_Confusion Matrixs.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

fpr, tpr, _ = roc_curve(y_true, y_prob)

auc_score = roc_auc_score(y_true, y_prob)

plt.figure(figsize=(6,5))

plt.plot(fpr, tpr, label=f"AUC = {auc_score:.4f}")

plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title("ResNet50 ROC Curve")

plt.legend()

plt.tight_layout()

plt.savefig(
    "ResNet50_ROC_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(y_true,y_pred))
print("Precision:", precision_score(y_true,y_pred))
print("Recall   :", recall_score(y_true,y_pred))
print("F1 Score :", f1_score(y_true,y_pred))
print("AUC      :", auc_score)

"""# Vision Transformer (ViT-B/16)"""

from torchvision import models
import torch.nn as nn

model = models.vit_b_16(
    weights=models.ViT_B_16_Weights.DEFAULT
)

model.heads.head = nn.Linear(
    model.heads.head.in_features,
    2
)

model = model.to(device)

print(model)

"""Parameters"""

import torch.optim as optim
from sklearn.metrics import accuracy_score

criterion = nn.CrossEntropyLoss()

optimizer = optim.AdamW(
    model.parameters(),
    lr=1e-4,
    weight_decay=1e-4
)

"""Training History"""

train_losses = []
val_losses = []

train_accs = []
val_accs = []

"""Training Function"""

from tqdm import tqdm

def train_vit(model, epochs=20):

    best_acc = 0

    for epoch in range(epochs):

        ####################
        # TRAIN
        ####################

        model.train()

        running_loss = 0

        train_true = []
        train_pred = []

        for images, labels in tqdm(train_loader):

            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            outputs = model(images)

            loss = criterion(
                outputs,
                labels
            )

            loss.backward()

            optimizer.step()

            running_loss += loss.item()

            preds = outputs.argmax(1)

            train_true.extend(
                labels.cpu().numpy()
            )

            train_pred.extend(
                preds.cpu().numpy()
            )

        train_loss = running_loss / len(train_loader)

        train_acc = accuracy_score(
            train_true,
            train_pred
        )

        ####################
        # VALIDATION
        ####################

        model.eval()

        val_running_loss = 0

        val_true = []
        val_pred = []

        with torch.no_grad():

            for images, labels in val_loader:

                images = images.to(device)
                labels = labels.to(device)

                outputs = model(images)

                loss = criterion(
                    outputs,
                    labels
                )

                val_running_loss += loss.item()

                preds = outputs.argmax(1)

                val_true.extend(
                    labels.cpu().numpy()
                )

                val_pred.extend(
                    preds.cpu().numpy()
                )

        val_loss = val_running_loss / len(val_loader)

        val_acc = accuracy_score(
            val_true,
            val_pred
        )

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch {epoch+1}: "
            f"Train Acc={train_acc:.4f} "
            f"Val Acc={val_acc:.4f}"
        )

        if val_acc > best_acc:

            best_acc = val_acc

            torch.save(
                model.state_dict(),
                "best_vit.pth"
            )

    print(
        "Best Validation Accuracy:",
        best_acc
    )

"""Train ViT"""

train_vit(
    model,
    epochs=10
)

"""Combined Accuracy + Loss Graph"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))

# Accuracy

plt.subplot(1,2,1)

plt.plot(
    train_accs,
    label='Train Accuracy'
)

plt.plot(
    val_accs,
    label='Validation Accuracy'
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.title(
    "ViT-B16 Accuracy"
)

plt.legend()

plt.grid(True)

# Loss

plt.subplot(1,2,2)

plt.plot(
    train_losses,
    label='Train Loss'
)

plt.plot(
    val_losses,
    label='Validation Loss'
)

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.title(
    "ViT-B16 Loss"
)

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.savefig(
    "ViT-B16_Training_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""Load Best Model"""

model.load_state_dict(
    torch.load(
        "best_vit.pth"
    )
)

"""Test Evaluation"""

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    roc_auc_score
)

y_true = []
y_pred = []
y_prob = []

model.eval()

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)

        outputs = model(images)

        probs = torch.softmax(
            outputs,
            dim=1
        )

        preds = outputs.argmax(1)

        y_true.extend(
            labels.numpy()
        )

        y_pred.extend(
            preds.cpu().numpy()
        )

        y_prob.extend(
            probs[:,1].cpu().numpy()
        )

"""Classification Report"""

print(
    classification_report(
        y_true,
        y_pred,
        target_names=[
            "Benign",
            "Malignant"
        ]
    )
)

"""Confusion Matrix"""

from sklearn.metrics import (
    ConfusionMatrixDisplay
)

cm = confusion_matrix(
    y_true,
    y_pred
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Benign",
        "Malignant"
    ]
)

disp.plot()

plt.title(
    "ViT-B16 Confusion Matrix"
)

plt.savefig(
    "ViT-B16_Confusion_Matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""ROC Curve"""

fpr, tpr, _ = roc_curve(
    y_true,
    y_prob
)

auc_score = roc_auc_score(
    y_true,
    y_prob
)

plt.figure(
    figsize=(6,5)
)

plt.plot(
    fpr,
    tpr,
    label=f"AUC = {auc_score:.4f}"
)

plt.plot(
    [0,1],
    [0,1],
    '--'
)

plt.xlabel(
    "False Positive Rate"
)

plt.ylabel(
    "True Positive Rate"
)

plt.title(
    "ViT-B16 ROC Curve"
)

plt.legend()

plt.savefig(
    "ViT-B16_ROC_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""Final Metrics"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print(
    "Accuracy:",
    accuracy_score(
        y_true,
        y_pred
    )
)

print(
    "Precision:",
    precision_score(
        y_true,
        y_pred
    )
)

print(
    "Recall:",
    recall_score(
        y_true,
        y_pred
    )
)

print(
    "F1 Score:",
    f1_score(
        y_true,
        y_pred
    )
)

print(
    "AUC:",
    auc_score
)

"""# Xception

Install & Import
"""

!pip install timm -q

import timm
import torch
import torch.nn as nn

"""Model Code"""

model = timm.create_model(
    'xception',
    pretrained=True,
    num_classes=2
)

model = model.to(device)

print(model)

"""Parameters"""

import torch.optim as optim
from sklearn.metrics import accuracy_score

criterion = nn.CrossEntropyLoss()

optimizer = optim.AdamW(
    model.parameters(),
    lr=1e-4,
    weight_decay=1e-4
)

"""Training History"""

train_losses = []
val_losses = []

train_accs = []
val_accs = []

"""Training Function"""

from tqdm import tqdm

def train_xception(model, epochs=10):

    best_acc = 0

    for epoch in range(epochs):

        # TRAIN
        model.train()

        running_loss = 0

        train_true = []
        train_pred = []

        for images, labels in tqdm(train_loader):

            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            outputs = model(images)

            loss = criterion(outputs, labels)

            loss.backward()

            optimizer.step()

            running_loss += loss.item()

            preds = outputs.argmax(1)

            train_true.extend(labels.cpu().numpy())
            train_pred.extend(preds.cpu().numpy())

        train_loss = running_loss / len(train_loader)

        train_acc = accuracy_score(
            train_true,
            train_pred
        )

        # VALIDATION
        model.eval()

        val_running_loss = 0

        val_true = []
        val_pred = []

        with torch.no_grad():

            for images, labels in val_loader:

                images = images.to(device)
                labels = labels.to(device)

                outputs = model(images)

                loss = criterion(outputs, labels)

                val_running_loss += loss.item()

                preds = outputs.argmax(1)

                val_true.extend(labels.cpu().numpy())
                val_pred.extend(preds.cpu().numpy())

        val_loss = val_running_loss / len(val_loader)

        val_acc = accuracy_score(
            val_true,
            val_pred
        )

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch {epoch+1}: "
            f"Train Acc={train_acc:.4f} "
            f"Val Acc={val_acc:.4f}"
        )

        if val_acc > best_acc:

            best_acc = val_acc

            torch.save(
                model.state_dict(),
                "best_xception.pth"
            )

    print(
        "Best Validation Accuracy:",
        best_acc
    )

"""Train Model"""

train_xception(
    model,
    epochs=10
)

"""Accuracy + Loss Graph"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))

# Accuracy
plt.subplot(1,2,1)

plt.plot(
    train_accs,
    label="Train Accuracy"
)

plt.plot(
    val_accs,
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.title(
    "Xception Accuracy"
)

plt.legend()
plt.grid(True)

# Loss
plt.subplot(1,2,2)

plt.plot(
    train_losses,
    label="Train Loss"
)

plt.plot(
    val_losses,
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.title(
    "Xception Loss"
)

plt.legend()
plt.grid(True)

plt.tight_layout()

plt.savefig(
    "Xception_Training_Curves.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()

"""Load Best Model"""

model.load_state_dict(
    torch.load(
        "best_xception.pth"
    )
)

"""Test Evaluation"""

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    roc_auc_score
)

y_true = []
y_pred = []
y_prob = []

model.eval()

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)

        outputs = model(images)

        probs = torch.softmax(
            outputs,
            dim=1
        )

        preds = outputs.argmax(1)

        y_true.extend(
            labels.numpy()
        )

        y_pred.extend(
            preds.cpu().numpy()
        )

        y_prob.extend(
            probs[:,1].cpu().numpy()
        )

"""Classification Report"""

print(
    classification_report(
        y_true,
        y_pred,
        target_names=[
            "Benign",
            "Malignant"
        ]
    )
)

"""Confusion Matrix"""

from sklearn.metrics import (
    ConfusionMatrixDisplay
)

cm = confusion_matrix(
    y_true,
    y_pred
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Benign",
        "Malignant"
    ]
)

disp.plot()

plt.title(
    "Xception Confusion Matrix"
)

plt.savefig(
    "Xception_Confusion_Matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""ROC Curve"""

fpr, tpr, _ = roc_curve(
    y_true,
    y_prob
)

auc_score = roc_auc_score(
    y_true,
    y_prob
)

plt.figure(figsize=(6,5))

plt.plot(
    fpr,
    tpr,
    label=f"AUC = {auc_score:.4f}"
)

plt.plot(
    [0,1],
    [0,1],
    '--'
)

plt.xlabel(
    "False Positive Rate"
)

plt.ylabel(
    "True Positive Rate"
)

plt.title(
    "Xception ROC Curve"
)

plt.legend()

plt.savefig(
    "Xception_ROC_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""Final Metrics"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(y_true, y_pred))
print("Precision:", precision_score(y_true, y_pred))
print("Recall   :", recall_score(y_true, y_pred))
print("F1 Score :", f1_score(y_true, y_pred))
print("AUC      :", auc_score)

"""# MobileNetV3"""

from torchvision import models
import torch.nn as nn

model = models.mobilenet_v3_large(
    weights=models.MobileNet_V3_Large_Weights.DEFAULT
)

model.classifier[3] = nn.Linear(
    model.classifier[3].in_features,
    2
)

model = model.to(device)

print(model)

"""Parameters"""

import torch.optim as optim
from sklearn.metrics import accuracy_score

criterion = nn.CrossEntropyLoss()

optimizer = optim.AdamW(
    model.parameters(),
    lr=1e-4,
    weight_decay=1e-4
)

"""Training History"""

train_losses = []
val_losses = []

train_accs = []
val_accs = []

"""Training Function"""

from tqdm import tqdm

def train_mobilenet(model, epochs=10):

    best_acc = 0

    for epoch in range(epochs):

        # TRAIN
        model.train()

        running_loss = 0

        train_true = []
        train_pred = []

        for images, labels in tqdm(train_loader):

            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            outputs = model(images)

            loss = criterion(outputs, labels)

            loss.backward()

            optimizer.step()

            running_loss += loss.item()

            preds = outputs.argmax(1)

            train_true.extend(labels.cpu().numpy())
            train_pred.extend(preds.cpu().numpy())

        train_loss = running_loss / len(train_loader)

        train_acc = accuracy_score(
            train_true,
            train_pred
        )

        # VALIDATION
        model.eval()

        val_running_loss = 0

        val_true = []
        val_pred = []

        with torch.no_grad():

            for images, labels in val_loader:

                images = images.to(device)
                labels = labels.to(device)

                outputs = model(images)

                loss = criterion(outputs, labels)

                val_running_loss += loss.item()

                preds = outputs.argmax(1)

                val_true.extend(labels.cpu().numpy())
                val_pred.extend(preds.cpu().numpy())

        val_loss = val_running_loss / len(val_loader)

        val_acc = accuracy_score(
            val_true,
            val_pred
        )

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch {epoch+1}: "
            f"Train Acc={train_acc:.4f} "
            f"Val Acc={val_acc:.4f}"
        )

        if val_acc > best_acc:

            best_acc = val_acc

            torch.save(
                model.state_dict(),
                "best_mobilenetv3.pth"
            )

    print(
        "Best Validation Accuracy:",
        best_acc
    )

"""Train Model"""

train_mobilenet(
    model,
    epochs=10
)

"""Combined Accuracy + Loss Graph"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))

# Accuracy
plt.subplot(1,2,1)

plt.plot(
    train_accs,
    label='Train Accuracy'
)

plt.plot(
    val_accs,
    label='Validation Accuracy'
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.title(
    "MobileNetV3 Accuracy"
)

plt.legend()
plt.grid(True)

# Loss
plt.subplot(1,2,2)

plt.plot(
    train_losses,
    label='Train Loss'
)

plt.plot(
    val_losses,
    label='Validation Loss'
)

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.title(
    "MobileNetV3 Loss"
)

plt.legend()
plt.grid(True)

plt.tight_layout()

plt.savefig(
    "MobileNetV3_Training_Curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""Load Best Model"""

model.load_state_dict(
    torch.load(
        "best_mobilenetv3.pth"
    )
)

"""Test Evaluation"""

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    roc_auc_score
)

y_true = []
y_pred = []
y_prob = []

model.eval()

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)

        outputs = model(images)

        probs = torch.softmax(
            outputs,
            dim=1
        )

        preds = outputs.argmax(1)

        y_true.extend(
            labels.numpy()
        )

        y_pred.extend(
            preds.cpu().numpy()
        )

        y_prob.extend(
            probs[:,1].cpu().numpy()
        )

"""Classification Report"""

print(
    classification_report(
        y_true,
        y_pred,
        target_names=[
            "Benign",
            "Malignant"
        ]
    )
)

"""Confusion Matrix"""

from sklearn.metrics import (
    ConfusionMatrixDisplay
)

cm = confusion_matrix(
    y_true,
    y_pred
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Benign",
        "Malignant"
    ]
)

disp.plot()

plt.title(
    "MobileNetV3 Confusion Matrix"
)

plt.savefig(
    "MobileNetV3_Confusion_Matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""ROC Curve"""

fpr, tpr, _ = roc_curve(
    y_true,
    y_prob
)

auc_score = roc_auc_score(
    y_true,
    y_prob
)

plt.figure(
    figsize=(6,5)
)

plt.plot(
    fpr,
    tpr,
    label=f"AUC = {auc_score:.4f}"
)

plt.plot(
    [0,1],
    [0,1],
    '--'
)

plt.xlabel(
    "False Positive Rate"
)

plt.ylabel(
    "True Positive Rate"
)

plt.title(
    "MobileNetV3 ROC Curve"
)

plt.legend()

plt.savefig(
    "MobileNetV3_ROC_Curves.png",
    dpi=300,
    bbox_inches="tight"
)


plt.show()

"""# Final Metrics"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print(
    "Accuracy:",
    accuracy_score(
        y_true,
        y_pred
    )
)

print(
    "Precision:",
    precision_score(
        y_true,
        y_pred
    )
)

print(
    "Recall:",
    recall_score(
        y_true,
        y_pred
    )
)

print(
    "F1 Score:",
    f1_score(
        y_true,
        y_pred
    )
)

print(
    "AUC:",
    auc_score
)

"""# Grad Cam ++"""

!pip install grad-cam -q

import torch
import numpy as np
import matplotlib.pyplot as plt

from pytorch_grad_cam import GradCAMPlusPlus
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget

model.load_state_dict(torch.load("best_mobilenetv3.pth"))
model.to(device)
model.eval()

target_layers = [model.features[-1]]

def prepare_image(img_tensor):

    img = img_tensor.permute(1, 2, 0).cpu().numpy()

    img = (img - img.min()) / (img.max() - img.min() + 1e-8)

    return img

images, labels = next(iter(test_loader))

image_tensor = images[0].unsqueeze(0).to(device)
label = labels[0].item()

from pytorch_grad_cam import GradCAMPlusPlus
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget

cam = GradCAMPlusPlus(
    model=model,
    target_layers=target_layers
)

model = model.to(device)
model.eval()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


target_layers = [model.features[-1]]

cam = GradCAMPlusPlus(
    model=model,
    target_layers=target_layers
)

images, labels = next(iter(test_loader))

img = images[0].unsqueeze(0).to(device)

targets = [ClassifierOutputTarget(labels[0].item())]

grayscale_cam = cam(
    input_tensor=img,
    targets=targets
)[0]

import matplotlib.pyplot as plt

def prepare_image(img_tensor):
    img = img_tensor.permute(1,2,0).cpu().numpy()
    img = (img - img.min()) / (img.max() - img.min() + 1e-8)
    return img

image = prepare_image(images[0])

visualization = show_cam_on_image(
    image,
    grayscale_cam,
    use_rgb=True
)

plt.imshow(visualization)
plt.axis("off")
plt.title("MobileNetV3 Grad-CAM++")
plt.savefig(
    "MobileNetV3_Grad_CAM_Plus.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()

"""## Final Comparison Table"""

import pandas as pd
import matplotlib.pyplot as plt

# Final Results
results = {
    "Model": [
        "Xception",
        "DenseNet121",
        "MobileNetV3",
        "ResNet50",
        "EfficientNetB0",
        "ViT-B/16"
    ],
    "Accuracy": [0.8148, 0.7946, 0.8005, 0.8005, 0.8005, 0.7500],
    "Precision": [0.8199, 0.7922, 0.8162, 0.8162, 0.8162, 0.7560],
    "Recall": [0.9140, 0.9244, 0.8918, 0.8918, 0.8918, 0.9048],
    "F1-score": [0.8644, 0.8532, 0.8523, 0.8523, 0.8523, 0.8237],
    "AUC": [0.8879, 0.8723, 0.8625, 0.8625, 0.8625, 0.8212]
}

df = pd.DataFrame(results)

# Sort by F1-score (optional)
df = df.sort_values("F1-score", ascending=False)

print(df)

# Create Table Figure
fig, ax = plt.subplots(figsize=(12, 3))
ax.axis('off')

table = ax.table(
    cellText=df.round(4).values,
    colLabels=df.columns,
    cellLoc='center',
    loc='center'
)

table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1.2, 1.6)

plt.title("Performance Comparison of Deep Learning Models on BreakHis Dataset",
          fontsize=12,
          pad=20)

plt.savefig(
    "Model_Comparison_Table.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()